src/objects/Dynamic_Page_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Determines whether to include this as part of the fields retrieved for the page.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Set_Name__c</fullName>
        <inlineHelpText>The API name of the field set that you wish to retrieve for display on the page.</inlineHelpText>
        <label>Field Set Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Columns__c</fullName>
        <defaultValue>3</defaultValue>
        <inlineHelpText>This is the number of columns that each section will have when displaying fields on the UI.</inlineHelpText>
        <label>Number of Columns</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <inlineHelpText>The API name of the object on which the field set exists.</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Order__c</fullName>
        <inlineHelpText>This determines which sections appear above/beneath other sections on the page.</inlineHelpText>
        <label>Section Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dynamic Page Mapping</label>
    <pluralLabel>Dynamic Page Mappings</pluralLabel>
</CustomObject>

src/classes/AccountManagementController.cls
public class AccountManagementController
{    
    @RemoteAction
	public static List<Dynamic_Page_Mapping__mdt> getPageMapping()
    {
        return [SELECT Id, Object_Name__c, Field_Set_Name__c, Section_Order__c, Number_of_Columns__c FROM Dynamic_Page_Mapping__mdt WHERE Active__c = true ORDER BY Section_Order__c ASC];
    }
    
    @RemoteAction
    public static Map<Id, List<FieldSetReactor.FieldDetails>> getFieldDetails(List<Dynamic_Page_Mapping__mdt> pageMapping)
    {
		Map<Id, List<FieldSetReactor.FieldDetails>> sectionFieldDetails = new Map<Id, List<FieldSetReactor.FieldDetails>>();
        
        for(Dynamic_Page_Mapping__mdt pageMap : pageMapping)
        {
            List<FieldSetReactor.FieldDetails> fieldDetails = FieldSetReactor.getFieldDetails(pageMap.Field_Set_Name__c, pageMap.Object_Name__c);
            sectionFieldDetails.put(pageMap.Id, fieldDetails);
        }
        
        return sectionFieldDetails;
    }
    
    @RemoteAction
    public static Account getAccount(Id accountId, List<String> fields)
    {
        String queryFields = String.join(fields, ',');
        String query = 'SELECT Id, ' + queryFields + ' FROM Account WHERE Id = \'' + accountId + '\'';
        
        return Database.query(query);
    }
    
    @RemoteAction
    public static List<Contact> getContacts(Id accountId, List<String> fields)
    {
        String queryFields = String.join(fields, ',');
        String query = 'SELECT Id, ' + queryFields + ' FROM Contact WHERE AccountId = \'' + accountId + '\'';
        
        return Database.query(query);
    }
    
    @RemoteAction
    public static List<Opportunity> getOpportunities(Id accountId, List<String> fields)
    {
        String queryFields = String.join(fields, ',');
        String query = 'SELECT Id, ' + queryFields + ' FROM Opportunity WHERE AccountId = \'' + accountId + '\'';
        
        return Database.query(query);
    }
}